brand: PRS
alt_brand: Paul Reed Smith
subbrand: S2
check_subbrand: True
ranges: [Custom 24, Custom 22, Standard 24, Standard 22, Singlecut, Mira, Starla, Vela]
year: 2018
store: themusiczoo
url: https://www.themusiczoo.com/collections/paul-reed-smith/electric-guitars+new+solid-body-electric?page=1
